### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### GET Products
GET http://localhost:3001/api/products


### POST contact with JSON body
POST http://localhost:3001/api/contact
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "email": "john.doe@example.com",
  "subject": "Hello — this is a test message from the HTTP client file."
}

### POST item to cart
POST http://localhost:3001/api/cart
Content-Type: application/json

{
    "name": "Left Handed Spiral Wrench",
    "price": 1234
}

### Get cart
GET http://localhost:3001/api/cart

### DELETE item from cart
DELETE http://localhost:3001/api/cart/2