### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST http://localhost:3001/contact

### POST contact with JSON body
POST http://localhost:3001/contact
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "email": "john.doe@example.com",
  "subject": "Hello — this is a test message from the HTTP client file."
}
